### ISSUE TITLE
Limited by CORS

### ISSUE THREAD

**Issue by abkfenris** [IrishMarineInstitute/erddap-leaflet-velocity-demo#4]
While this now uses a JSONP formatted response, it doesn't get around CORS when accessing other ERDDAP servers as it still is using the `fetch` API. 

https://github.com/IrishMarineInstitute/erddap-leaflet-velocity-demo/blob/643186f6950efef5d86f3c4f889d298fd0292a37/erddapToLeafletVelocity.js#L18-L27

JSONP gets around CORS by loading data within a script tag and when the script finishes loading it fires the JSONP callback function (`erddapData`) that it has been wrapped in.

Starting with [this](https://stackoverflow.com/a/48916211/3658919), this function will work to load JSONP data from ERDDAP and return a Promise, that you can `.then(` off of and not be limited by CORS.

```javascript
function jsonp(url) {
    return new Promise(function(resolve, reject) {
        let script = document.createElement('script')
        const name = "_jsonp_" + Math.round(100000 * Math.random());
        //url formatting
        if (url.match(/\?/)) url += "&.jsonp="+name
        else url += "&.jsonp="+name
        script.src = url;

        window[name] = function(data) {
            resolve(data);
            document.body.removeChild(script);
            delete window[name];
        }
        document.body.appendChild(script);
    });
}
```

I believe a remaining limitation will be when accessing http from https sites as that will be blocked by mixed content.

Re #1

**Comment by adamml** [comment]
@abkfenris I've updated for CORS now using your function as above, many thanks for that. I think we can close this issue now - although as you say mixed content may remain an issue.
